services:
  secure-2fa:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data_volume:/data
      - ./cron_volume:/cron
    environment:
      - PRIVATE_KEY_PATH=/app/private_key.pem
    restart: always
